http:
  port: 8888

server:
  port: 8443
  ssl:
    key-store: classpath:security/https.keystore
    key-store-password: Yue123456
    key-password: Yue123456
    key-store-type: JKS
spring:
  redis:
    host: localhost
    port: 6792
    database: 0
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
      #连接超时时间
      timeout: 10000
  servlet:
        multipart:
          enabled: true
          max-file-size: 20MB
          max-request-size: 200MB

